pipeline:
  name: dotnet-cache-test-google
  identifier: dotnetcachetestgoogle
  projectIdentifier: tiagentdev
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: avijeetdotnetcachetest
        build: <+input>
  stages:
    - stage:
        name: test
        identifier: test
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          caching:
            enabled: true
            paths: []
          buildIntelligence:
            enabled: false
          platform:
            os: Windows
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Run
                  name: Run_1
                  identifier: Run_1
                  spec:
                    shell: Sh
                    command: dotnet test
